### ISSUE TITLE
Items with modifiers relying on Self:GetCaster() will bug when the applying item is destroyed

### ISSUE THREAD

**Issue by Celireor** [ark120202/angel-arena-black-star#299]
1 - Get 5 book of the guardian
2 - Go near boss
3 - Destroy the aura applier (you have to guess)
If you have at least 1 book left and u got lucky you will receive this error

Script Runtime Error: ...tar\scripts\vscripts\items\item_book_of_the_guardian.lua:127: attempt to index a nil value
stack traceback:
	...tar\scripts\vscripts\items\item_book_of_the_guardian.lua:127: in function <...tar\scripts\vscripts\items\item_book_of_the_guardian.lua:126>
Message count limit of 10 hit. Subsequent duplicate messages will be squelched.

**Comment by ark120202** [comment]
In that case the problem is self:GetAbility(), not GetCaster: https://github.com/ark120202/angel-arena-black-star/blob/32533a55ec908d225cd772b77d1a123d50887245/game/scripts/vscripts/items/item_book_of_the_guardian.lua#L127

That may solve it https://github.com/ark120202/angel-arena-black-star/blob/8a0fee8ad69a19b467c63b62eae267b24c37d64b/game/scripts/vscripts/util/shared.lua#L19-L29

Still, I don't think there's a reason to waste time solving it now. It shouldn't really affect gameplay. With new build system items would be declared in a different way, so then it would be fixed.
