### ISSUE TITLE
Should timers be re-wrote so all timers are arranged in endtime order and only the first one need to be tested?

### ISSUE THREAD

**Issue by Celireor** [ark120202/angel-arena-black-star#321]
That would move most of the checking stage from the timers tick phase to the timers create stage

**Comment by ark120202** [comment]
> Should timers be re-wrote

Yes, like all used libraries (#181, #182, #184). And even not only libraries, but also modules, because of a new module format in 2.0.

> all timers are arranged in endtime order and only the first one need to be tested

What do you mean? Rearranging a big array on each new timer isn't really performant.
Or do you want to have a map with a key of end time? But in that case how it should be iterated?

**Comment by Celireor** [comment]
https://github.com/ark120202/angel-arena-black-star/pull/424
