### ISSUE TITLE
How to close generator without permanently breaking it?

### ISSUE THREAD

**Issue by Celireor** [ark120202/angel-arena-black-star#422]
i cant seem to close the generator without breaking it

**Comment by ark120202** [comment]
The actual issue isn't closing, but it's startup. To solve it you can try to change `delay` in generator settings. When it's value is too low it swaps the fake directory and symlink too early, so dota won't be able to load the addon and fallback to default addon selection screen (without aabs in it). When it's too big dota would lock the fake directory and script won't be able to rename symlink, leaving it in the invalid state.

Of course it's far from ideal solution (when I made it I hoped valve would fix it soon). It's already fixed in 2.0 build chain, but it's far from being done. If changing delay won't help maybe for now it can be switched to [revserse-symlinking](https://github.com/darklordabc/overthrow2/blob/736fccf56700d3c5cfe45d94457197c6c743eb7c/install.js) solution.
